
server:
  port: 8082
spring:
  application:
    name: gateway_server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
          #开启小写验证，默认feign根据服务名查找都是用的全大写
          lowerCaseServiceId: true
      routes:
        - id: user-route
          uri: lb://nacos-user-service
          # 断言,路径相匹配的进行路由
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: order-route
          uri: lb://nacos-order-service
          # 断言,路径相匹配的进行路由
          predicates:
            - Path=/order/**
          filters:
#            - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: "*"