server:
  port: 8207
spring:
  application:
    name: nacos-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
        ip: 127.0.0.1
    sentinel:
      transport:
        dashboard: localhost:8080 #配置sentinel dashboard地址
        port: 8719
      filter:
        enabled: false
management:
  endpoints:
    web:
      exposure:
        include: '*'